# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=4096)),
                ('price_desc', models.CharField(max_length=4096)),
                ('players_desc', models.CharField(max_length=4096)),
                ('age_desc', models.CharField(max_length=4096)),
                ('players_min', models.IntegerField(default=2)),
                ('players_max', models.IntegerField(default=4)),
                ('rating', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('duration_min', models.IntegerField(default=60)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 7, 12, 17, 13, 0, 316682), verbose_name='date created')),
            ],
        ),
    ]
