# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import quest.models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveDoc',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('img-p', 'Image of Players'), ('img-o', 'Image of Other')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField(max_length=4096)),
                ('type', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=quest.models.page_image_directory_path)),
                ('type', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Page')),
            ],
        ),
        migrations.CreateModel(
            name='QuestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=quest.models.quest_image_directory_path)),
                ('type', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='in_construct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='age_desc',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='players_desc',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='quest',
            name='price_desc',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='questimage',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Quest'),
        ),
    ]
