# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import quest.models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20160906_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('image', models.ImageField(upload_to=quest.models.discount_image_directory_path)),
                ('type', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
