# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_discounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discount',
        ),
    ]
