# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20160908_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='desc',
            field=models.TextField(default='', max_length=4096),
        ),
    ]
