# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_discount_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
