# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_quest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='age_value',
            field=models.IntegerField(default=0),
        ),
    ]
