# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_quest_age_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget', models.TextField(max_length=4096)),
                ('desc', models.TextField(default='', max_length=4096)),
                ('type', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
