# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quest.Quest'),
            preserve_default=False,
        ),
    ]
