# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0010_auto_20160926_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='seo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
