# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0011_quest_seo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
