# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0013_auto_20161123_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='banners')),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
