# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0014_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
