# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0015_quest_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(blank=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
