# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0016_auto_20170120_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
