# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0017_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
