# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0018_auto_20170120_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='players_add',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
