# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0019_quest_players_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_animator',
            field=models.BooleanField(default=True),
        ),
    ]
