# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0020_quest_is_animator'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='title_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
