# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0023_quest_is_with_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slide_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
