# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0024_auto_20171006_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slide_delay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Slide delay'),
        ),
    ]
