# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import quest.models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0025_auto_20171006_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=4096)),
                ('title_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title', models.CharField(max_length=255, null=True)),
                ('seo_description', models.TextField(max_length=4096, null=True)),
                ('seo_url', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('price_desc', models.CharField(default='', max_length=4096)),
                ('players_desc', models.CharField(default='', max_length=4096)),
                ('age_desc', models.CharField(default='', max_length=4096)),
                ('age_value', models.IntegerField(default=0)),
                ('players_min', models.IntegerField(default=2)),
                ('players_max', models.IntegerField(default=4)),
                ('players_add', models.IntegerField(blank=True, default=3)),
                ('duration_min', models.IntegerField(default=60)),
                ('in_construct', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_with_actor', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_animator', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ShowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=quest.models.show_image_directory_path)),
                ('type', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Show')),
            ],
        ),
        migrations.CreateModel(
            name='VideoShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget', models.TextField(max_length=4096)),
                ('desc', models.TextField(default='', max_length=4096)),
                ('type', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Show')),
            ],
        ),
    ]
